services:
  nginx:
    image: nginx:1.25-bookworm
    container_name: nginx-odoo
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/obsidian.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
 

